2025-05-16 01:33:56,025 INFO    MainThread:3799583 [wandb_setup.py:_flush():67] Current SDK version is 0.19.9
2025-05-16 01:33:56,025 INFO    MainThread:3799583 [wandb_setup.py:_flush():67] Configure stats pid to 3799583
2025-05-16 01:33:56,025 INFO    MainThread:3799583 [wandb_setup.py:_flush():67] Loading settings from /sdf/home/c/carsmith/.config/wandb/settings
2025-05-16 01:33:56,025 INFO    MainThread:3799583 [wandb_setup.py:_flush():67] Loading settings from /sdf/home/c/carsmith/PILArNet-ML/3d_segment/wandb/settings
2025-05-16 01:33:56,025 INFO    MainThread:3799583 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-05-16 01:33:56,026 INFO    MainThread:3799583 [wandb_init.py:setup_run_log_directory():662] Logging user logs to /sdf/home/c/carsmith/PILArNet-ML/3d_segment/wandb/run-20250516_013356-llt9w1uv/logs/debug.log
2025-05-16 01:33:56,026 INFO    MainThread:3799583 [wandb_init.py:setup_run_log_directory():663] Logging internal logs to /sdf/home/c/carsmith/PILArNet-ML/3d_segment/wandb/run-20250516_013356-llt9w1uv/logs/debug-internal.log
2025-05-16 01:33:56,026 INFO    MainThread:3799583 [wandb_init.py:monkeypatch_ipython():581] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7f7604040250>
2025-05-16 01:33:56,026 INFO    MainThread:3799583 [wandb_init.py:init():781] calling init triggers
2025-05-16 01:33:56,026 INFO    MainThread:3799583 [wandb_init.py:init():786] wandb.init called with sweep_config: {}
config: {'epochs': 1, 'batch_size': 128, 'lr': 0.0001, '_wandb': {}}
2025-05-16 01:33:56,026 INFO    MainThread:3799583 [wandb_init.py:init():809] starting backend
2025-05-16 01:33:56,026 INFO    MainThread:3799583 [wandb_init.py:init():813] sending inform_init request
2025-05-16 01:33:56,031 INFO    MainThread:3799583 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-05-16 01:33:56,031 INFO    MainThread:3799583 [wandb_init.py:init():823] backend started and connected
2025-05-16 01:33:56,034 INFO    MainThread:3799583 [wandb_run.py:_label_probe_notebook():1267] probe notebook
2025-05-16 01:33:56,035 INFO    MainThread:3799583 [wandb_run.py:_label_probe_notebook():1277] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2025-05-16 01:33:56,035 INFO    MainThread:3799583 [wandb_init.py:init():915] updated telemetry
2025-05-16 01:33:56,050 INFO    MainThread:3799583 [wandb_init.py:init():939] communicating run to backend with 90.0 second timeout
2025-05-16 01:33:56,486 INFO    MainThread:3799583 [wandb_init.py:init():1014] starting run threads in backend
2025-05-16 01:33:56,783 INFO    MainThread:3799583 [wandb_run.py:_console_start():2454] atexit reg
2025-05-16 01:33:56,783 INFO    MainThread:3799583 [wandb_run.py:_redirect():2306] redirect: wrap_raw
2025-05-16 01:33:56,783 INFO    MainThread:3799583 [wandb_run.py:_redirect():2371] Wrapping output streams.
2025-05-16 01:33:56,783 INFO    MainThread:3799583 [wandb_run.py:_redirect():2394] Redirects installed.
2025-05-16 01:33:56,787 INFO    MainThread:3799583 [wandb_init.py:init():1056] run started, returning control to user process
2025-05-16 01:33:56,896 INFO    MainThread:3799583 [wandb_watch.py:_watch():71] Watching
2025-05-16 01:33:57,211 INFO    MainThread:3799583 [jupyter.py:save_ipynb():384] [no run ID] not saving jupyter notebook
2025-05-16 01:33:57,211 INFO    MainThread:3799583 [wandb_init.py:_pause_backend():546] [no run ID] pausing backend
2025-05-16 01:34:40,855 INFO    MainThread:3799583 [wandb_init.py:_resume_backend():551] [no run ID] resuming backend
2025-05-16 01:34:40,932 INFO    MainThread:3799583 [jupyter.py:save_ipynb():384] [no run ID] not saving jupyter notebook
2025-05-16 01:34:40,932 INFO    MainThread:3799583 [wandb_init.py:_pause_backend():546] [no run ID] pausing backend
2025-05-16 01:38:39,789 INFO    MsgRouterThr:3799583 [mailbox.py:close():129] [no run ID] Closing mailbox, abandoning 1 handles.
2025-05-16 01:38:40,364 ERROR   Thread-2 (_watch_pipe_fd):3799583 [redirect.py:_on_write():661] [no run ID] error in stdout callback
Traceback (most recent call last):
  File "/sdf/home/c/carsmith/.local/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/sdf/home/c/carsmith/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2375, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
  File "/sdf/home/c/carsmith/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/sdf/home/c/carsmith/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/sdf/home/c/carsmith/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/sdf/home/c/carsmith/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/sdf/home/c/carsmith/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/sdf/home/c/carsmith/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/sdf/home/c/carsmith/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/sdf/home/c/carsmith/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/sdf/home/c/carsmith/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/sdf/home/c/carsmith/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
